export const cssVariables = {
  colors: [
    { name: "--color-primary", light: "#F57070", dark: "#F57070" },
    { name: "--color-secondary", light: "#3540df", dark: "#3540df" },
    { name: "--color-tertiary", light: "#2AB885", dark: "#2AB885" },
    { name: "--color-quaternary", light: "#FBC473", dark: "#FBC473" },
    { name: "--color-dark", light: "#0f0f36", dark: "#ffffff" },
    { name: "--color-gray9", light: "#17174F", dark: "#F8F8FC" },
    { name: "--color-gray8", light: "#26256C", dark: "#f2f2f7" },
    { name: "--color-gray7", light: "#494880", dark: "#DEDEE9" },
    { name: "--color-gray6", light: "#6D6D9C", dark: "#D2D2E2" },
    { name: "--color-gray5", light: "#9E9ECC", dark: "#9E9ECC" },
    { name: "--color-gray4", light: "#D2D2E2", dark: "#6D6D9C" },
    { name: "--color-gray3", light: "#DEDEE9", dark: "#494880" },
    { name: "--color-gray2", light: "#f2f2f7", dark: "#26256C" },
    { name: "--color-gray1", light: "#F8F8FC", dark: "#17174F" },
    { name: "--color-light", light: "#ffffff", dark: "#17174F" },
  ],
  fonts: [
    { name: "--font-primary", value: "Roboto" },
    { name: "--font-secondary", value: "Poppins" },
    { name: "--font-tertiary", value: "Playfair Display" },
    { name: "--font-quaternary", value: "Roboto Mono" },
  ],
};
